FUNCTION FN_FE_UserADD
(
    P_BELONGER FE_FUNDSCLEARINGACCOUNT.BELONGER%TYPE,                              
    P_BELONGERTYPE FE_FUNDSCLEARINGACCOUNT.BELONGERTYPE%TYPE,                      
    P_FUNDPASSWORD FE_FUNDSCLEARINGACCOUNT.FUNDSPASSWORD%TYPE,                     
    P_FUNDCLEARINGACCOUNTID  FE_FUNDSCLEARINGACCOUNT.FUNDSCLEARINGACCOUNTID%TYPE   
)
RETURN NUMBER











AS
  V_DEFAULTID                      NUMBER(32):=100000000000;
  V_USERCODE                       NUMBER(32);                   
  V_CNT                            NUMBER(4);
  V_FUNDSCLEARINGACCOUNTID         NUMBER(32):=0;                
  V_FUNDSCLEARINGACCOUNTIDSTRING   VARCHAR(32);                  
  V_FUNDSACCOUNTID                 NUMBER(32);
  V_NO                             NUMBER(2):=10;                
BEGIN

  
  IF(P_FUNDCLEARINGACCOUNTID IS NOT NULL) THEN
    V_FUNDSCLEARINGACCOUNTID:=P_FUNDCLEARINGACCOUNTID;
    V_FUNDSCLEARINGACCOUNTIDSTRING:=P_FUNDCLEARINGACCOUNTID;
    
    V_USERCODE:=SUBSTR(V_FUNDSCLEARINGACCOUNTID,0,8);
    
    SELECT COUNT(1) INTO V_CNT FROM  FE_USERANDACCOUNTCL WHERE BELONGER = P_BELONGER AND BELONGERTYPE = P_BELONGERTYPE;
    IF(V_CNT = 0) THEN
      INSERT INTO FE_USERANDACCOUNTCL (BELONGER, BELONGERTYPE, FUNDSCLEARINGACCOUNTID) VALUES (P_BELONGER, P_BELONGERTYPE, V_FUNDSCLEARINGACCOUNTID);
    END IF;
  ELSE
    
    SELECT COUNT(1) INTO V_CNT FROM FE_FUNDSCLEARINGACCOUNT WHERE BELONGER = P_BELONGER AND BELONGERTYPE = P_BELONGERTYPE;
    IF(V_CNT = 0) THEN
      
      SELECT SEQ_FE_FUNDSCLEARINGACCOUNT.NEXTVAL INTO V_FUNDSCLEARINGACCOUNTID FROM DUAL;
      V_FUNDSCLEARINGACCOUNTID:= V_DEFAULTID + (V_FUNDSCLEARINGACCOUNTID * 10000);      
      V_FUNDSCLEARINGACCOUNTIDSTRING:=V_FUNDSCLEARINGACCOUNTID;
      INSERT INTO FE_FUNDSCLEARINGACCOUNT (FUNDSCLEARINGACCOUNTID,  FUNDSPASSWORD,   BELONGER,  BELONGERTYPE)
                                  VALUES (V_FUNDSCLEARINGACCOUNTID,FN_FE_MD5(FN_FE_MD5(P_FUNDPASSWORD || V_FUNDSCLEARINGACCOUNTID)), P_BELONGER,P_BELONGERTYPE);
    ELSE
      SELECT FUNDSCLEARINGACCOUNTID INTO V_FUNDSCLEARINGACCOUNTID FROM FE_FUNDSCLEARINGACCOUNT WHERE BELONGER = P_BELONGER AND BELONGERTYPE = P_BELONGERTYPE;
    END IF;

    
    V_USERCODE:=SUBSTR(V_FUNDSCLEARINGACCOUNTID,0,8);

    
    SELECT COUNT(1) INTO V_CNT FROM CL_ACCOUNT WHERE CODE='200100' || V_USERCODE; 
    IF(V_CNT=0)THEN
       INSERT INTO CL_ACCOUNT (CODE,NAME,ACCOUNTLEVEL,DCFLAG,ISINIT)
              SELECT '200100' || V_USERCODE,NAME || V_USERCODE, 3, DCFLAG,'Y' FROM CL_ACCOUNT WHERE CODE='200100';
    END IF;

    
    SELECT COUNT(1) INTO V_CNT FROM CL_ACCOUNT WHERE CODE='200100' || V_FUNDSCLEARINGACCOUNTID; 
    IF(V_CNT=0)THEN
       INSERT INTO CL_ACCOUNT (CODE,NAME,ACCOUNTLEVEL,DCFLAG,ISINIT)
              SELECT '200100' || V_FUNDSCLEARINGACCOUNTID,NAME || V_USERCODE || '资金结算账户',4,DCFLAG,'Y' FROM CL_ACCOUNT WHERE CODE='200100';
    END IF;
  END IF;


  IF(V_FUNDSCLEARINGACCOUNTID <> 0) THEN
    
    SELECT COUNT(1) INTO V_CNT FROM FE_FUNDSACCOUNT WHERE BELONGER = P_BELONGER AND BELONGERTYPE = P_BELONGERTYPE;
    IF(V_CNT = 0) THEN 
       
       SELECT COUNT(1) INTO V_CNT FROM FE_FUNDSACCOUNT WHERE FUNDSCLEARINGACCOUNTID = V_FUNDSCLEARINGACCOUNTIDSTRING;
       IF(V_CNT > 0) THEN
         
         SELECT SUBSTR(MAX(F.FUNDSACCOUNTID),11) INTO V_NO FROM FE_FUNDSACCOUNT F WHERE FUNDSCLEARINGACCOUNTID = V_FUNDSCLEARINGACCOUNTIDSTRING;
         V_NO:= V_NO + 1;
       END IF;
       FOR FUNDACCOUNT IN (SELECT * FROM FE_FUNDSACCOUNTTYPE)
         LOOP
           V_FUNDSACCOUNTID:=V_FUNDSCLEARINGACCOUNTID + (FUNDACCOUNT.FUNDSACCOUNTTYPEID*100) + V_NO;  
           INSERT INTO FE_FUNDSACCOUNT (FUNDSACCOUNTID,  BELONGER,   BELONGERTYPE, FUNDSCLEARINGACCOUNTID,    FUNDSACCOUNTTYPEID)
                               VALUES (V_FUNDSACCOUNTID, P_BELONGER,P_BELONGERTYPE,V_FUNDSCLEARINGACCOUNTID, FUNDACCOUNT.FUNDSACCOUNTTYPEID);

           
           SELECT COUNT(1) INTO V_CNT FROM CL_ACCOUNT WHERE CODE='200100' || SUBSTR(V_FUNDSACCOUNTID,0,10); 
           IF(V_CNT=0)THEN
              INSERT INTO CL_ACCOUNT (CODE,NAME,ACCOUNTLEVEL,DCFLAG,ISINIT)
                         SELECT '200100' || SUBSTR(V_FUNDSACCOUNTID,0,10),NAME || V_USERCODE || '资金账户(' || FUNDACCOUNT.FUNDSACCOUNTTYPEID ||  ')', 4, DCFLAG,'Y' FROM CL_ACCOUNT WHERE CODE='200100';
           END IF;

           
           SELECT COUNT(1) INTO V_CNT FROM CL_ACCOUNT WHERE CODE='200100' || V_FUNDSACCOUNTID; 
           IF(V_CNT=0)THEN
              INSERT INTO CL_ACCOUNT (CODE,NAME,ACCOUNTLEVEL,DCFLAG,ISINIT)
                         SELECT '200100' || V_FUNDSACCOUNTID,NAME || V_USERCODE || '资金账户(' || FUNDACCOUNT.FUNDSACCOUNTTYPEID ||  ')' || V_NO, 5, DCFLAG,'Y' FROM CL_ACCOUNT WHERE CODE='200100';
           END IF;
         END LOOP;
       
       FOR SYSANDACCOUNT IN (SELECT FS.SYSTEMID,FF.FUNDSACCOUNTID FROM FE_SYSANDACCOUNT FS,FE_FUNDSACCOUNT FF WHERE BELONGER = P_BELONGER AND BELONGERTYPE = P_BELONGERTYPE AND  FS.FUNDSACCOUNTTYPEID = FF.FUNDSACCOUNTTYPEID(+))
        LOOP
          INSERT INTO FE_USERANDACCOUNT (ACCOUNTRELATIONID,            BELONGER,  BELONGERTYPE,  FUNDSACCOUNTID,                        SYSTEMID)
                                 VALUES (SEQ_FE_USERANDACCOUNT.NEXTVAL,P_BELONGER,P_BELONGERTYPE,SYSANDACCOUNT.FUNDSACCOUNTID,SYSANDACCOUNT.SYSTEMID);
        END LOOP;
    END IF;
  END IF;
  RETURN 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RETURN -99;  
    WHEN OTHERS THEN
    SP_CL_DBLOG('FN_FE_UserADD', SQLCODE, SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    ROLLBACK;
    RETURN -100;
END;